---
abstract: 'Common interface to Growl'
author:
  - 'Yasuhiro Matsumoto <mattn.jp@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  IO::Handle: 0
  Test::More: 0
  parent: 0
configure_requires:
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Growl-Any
provides: {}
requires:
  LWP::UserAgent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/mattn/p5-Growl-Any/issues
  homepage: https://github.com/mattn/p5-Growl-Any
  repository: git://github.com/mattn/p5-Growl-Any.git
version: 0.10
